First commit for code review, without Unit Tests
andreeaiulia13/Assignment2 pull request #1
Opened 2021-04-19 11:41 UTC by andreeaiulia13

2021-04-20 12:59 UTC, VictorMotogna requested changes

2021-04-20 12:59 UTC, VictorMotogna commented on car_cleaning_service.rb
> +  @@cars = Array.new
Having a list of cars inside the car model is a little confusing. Maybe having this variable outside the class:

```ruby
cars = []

class Car
  def initialize; end
end

cars << Car.new() # call this multiple times to add cars
```

2021-04-20 12:59 UTC, VictorMotogna commented on car_cleaning_service.rb
> +  if (name[/[a-zA-Z]*/] != name)
Maybe having a regex & using `match` would be cleaner here

2021-04-20 12:59 UTC, VictorMotogna commented on car_cleaning_service.rb
> +def check_car_status
I think you should try to space lines a little bit, so it would be easier to read. Having spaces before ifs/loops, separating blocks of code, etc..

2021-04-20 12:59 UTC, VictorMotogna commented on car_cleaning_service.rb
> +  Car.all.each{ |car|
you would already have access to list of cars here (@@cars), so you could use that. in Rails, if you'd already have this list and use `Car.all` that would make a new query to the database, which is unnecessary

2021-04-20 12:59 UTC, VictorMotogna commented on car_cleaning_service.rb
> +      pres = 1
I think that `pres` is not really an intuitive name, and also you could change it to a boolean, it would be easier to understand it's purpose

2021-04-20 12:59 UTC, VictorMotogna commented on car_cleaning_service.rb
> +  if Time.new(2021, month, day, hour, min, 0) < Time.now
Maybe having a `case when` here wold make things more readable.

2021-04-20 12:59 UTC, VictorMotogna commented on car_cleaning_service.rb
> +end
I think that a little refactoring for spacing would help: newlines between blocks/ifs/loops, adding a newline at the end of the file

2021-04-20 14:14 UTC, vaneaclaudia requested changes

2021-04-20 14:14 UTC, vaneaclaudia commented on car_cleaning_service.rb
> +  attr_reader :drop_time
you can add `user_name` and `drop_time` on the same line like this:

`attr_reader :user_name, drop_time`

2021-04-20 14:14 UTC, vaneaclaudia commented on car_cleaning_service.rb
> +  Car.all.each{ |car|
try do use `Car.all.each do ...end` when you have a multi line block. 
Usually for multi line blocks it is recommended to use do..end block and for single line block {}

2021-04-20 14:14 UTC, vaneaclaudia commented on car_cleaning_service.rb
> +    if (car.user_name == name)
instead of having so many `if` conditions you can use here `next unless car.user_name == name`
also no need to use parentheses

2021-04-20 14:14 UTC, vaneaclaudia commented on car_cleaning_service.rb
> +end
I agree with @VictorMotogna. Empty lines between block will improve readability

2021-04-22 13:44 UTC, VictorMotogna requested changes

2021-04-22 13:44 UTC, VictorMotogna commented on Controler/controler.rb
> +require "/home/andreea/Desktop/Assignment2_CarCleaningService/Model/model.rb"
You should try to use `require_relative`. If I pull this code and run it on my machine, it will not work, because I don't have this path on my machine

2021-04-22 13:44 UTC, VictorMotogna commented on Model/model.rb
> +$cars = []
You don't need to add `$` to variable names

2021-04-22 13:44 UTC, VictorMotogna commented on Controler/controler.rb
> +  $cars.each {|car| count_cars_in_a_time_interval += 1 if ((car.drop_time > time && car.drop_time < time + 7200) || (car.pickup_time > time && car.pickup_time < time + 7200))}
you could add a space before & after `{}`:
```ruby
cars.each { |car| c.do_something }
```

2021-04-22 13:44 UTC, VictorMotogna commented on Controler/controler.rb
> +  if !name.match(regular_name)
you can refactor to use `unless name.match`

2021-04-22 13:44 UTC, VictorMotogna commented on Controler/controler.rb
> +	end
the indentation of this `end` seems a little bit off

2021-04-22 13:44 UTC, VictorMotogna commented on View/view.rb
> +while(option != 5)
it seems like the `6` is the exit command, not 5

2021-04-22 13:44 UTC, VictorMotogna commented on spec/car_service_spec.rb
> +	context "when sunday" do
the indentation in this file seems to be 4 spaces, it looks like it's different than the rest of the files

2021-04-22 13:48 UTC, vaneaclaudia requested changes

2021-04-22 13:48 UTC, vaneaclaudia commented on Controler/controler.rb
> +
if you want to follow the MVC pattern, then you should have your folders named like controllers/models/views

2021-04-22 13:48 UTC, vaneaclaudia commented on Controler/controler.rb
> + return ((time.sunday?) || (time.hour < 8) || ((time + 7200).hour >= 18) || ((time + 7200).hour == 0)|| ((time.saturday?) && ((time + 7200).hour >= 16)))
You don't need to use return since it's the only line of code you have. You should use `return` keyword when you have multiple blocks of code and you want to return from the method if some conditions are met. 
Also, this line with conditions is very hard to follow. I suggest splitting these in 2 methods

2021-04-22 13:48 UTC, vaneaclaudia commented on Controler/controler.rb
> +  return false
same remark here regarding redundant `return`

2021-04-22 13:48 UTC, vaneaclaudia commented on Controler/controler.rb
> +  $cars.each {|car| puts "Drop time: #{car.drop_time.strftime("%d %B %Y %H:%M")}, Pick up time: #{car.pickup_time.strftime("%H:%M")}" if car.pickup_time > Time.now}
I suggest you use a `do..end` block here, it will be easier to follow the code since the line is so long

2021-04-22 13:48 UTC, vaneaclaudia commented on spec/car_service_spec.rb
> +describe "check open times" do
please use single quotes instead of double quotes, usually double quotes are used when you have interpolation

2021-04-22 13:48 UTC, vaneaclaudia commented on spec/car_service_spec.rb
> +		time = Time.new(2021, 04, 25, 9, 00, 0)
this could be a let variable

let(:time) { Time.new(2021, 04, 25, 9, 00, 0) }

2021-04-22 13:48 UTC, vaneaclaudia commented on spec/car_service_spec.rb
> +		it "return true" do
same remark using single quotes

2021-04-22 13:48 UTC, vaneaclaudia commented on spec/car_service_spec.rb
> +		time = Time.new(2021, 04, 24, 16, 00, 0)
same remark using let variable

2021-04-22 13:48 UTC, vaneaclaudia commented on spec/car_service_spec.rb
> +		end
since you have only one line of code you can do something like:

`before { $cars = $cars.clear() }`

2021-04-22 15:27 UTC, andreeaiulia13 commented on Model/model.rb
> +$cars = []
It gives me an error if I don't use "$" :undefined local variable or method `cars' for main:Object (NameError)

2021-04-23 06:50 UTC, VictorMotogna commented on Model/model.rb
> +$cars = []
ok, I see, my bad. in that case, you can use it like this

2021-04-23 08:55 UTC, VictorMotogna requested changes

2021-04-23 08:55 UTC, VictorMotogna commented on controllers/controller.rb
> +  when Time.new(2021, month, day, hour, min, 0) < Time.now
you can move `Time.new(2021, month, day, hour, min, 0)` to a variable, so you won't instantiate for each check

2021-04-23 08:55 UTC, VictorMotogna commented on spec/service_spec.rb
> +
the indentation in this file seems to be 4 spaces

2021-04-23 08:55 UTC, VictorMotogna commented on spec/service_spec.rb
> +end
you'll need to add a newline at the end of the file

2021-04-23 11:14 UTC, VictorMotogna approved these changes

2021-04-26 06:54 UTC, vaneaclaudia approved these changes
Good job! 👍 💯

2021-04-26 07:22 UTC, merged